### ISSUE TITLE
jsrasign vulnerability in 0.0.2

### ISSUE THREAD

**Issue by jmecosta** [trimble-oss/trimble-id-sdk-docs-for-js#1]
Hi

maybe you could update it
"@trimble-oss/trimble-id@^0.0.2":
  version "0.0.2"
  resolved "https://registry.yarnpkg.com/@trimble-oss/trimble-id/-/trimble-id-0.0.2.tgz#209e711eb268e1e07ade76581419b2e6d5895bed"
  integrity sha512-0UvJhFQqc+P1JWehPVmTNY/K5gUcIiz2LOteKGmBNu1Sf1/mXtRJMJ2E5TqX2gG6iB4MBDrpHLKNJ09JnNVFVQ==
  dependencies:
    axios "^1.6.2"
    btoa "^1.2.1"
    jsrsasign "^10.2.0"
    uuid "^9.0.0 "

<img width="1819" alt="image" src="https://github.com/trimble-oss/trimble-id-sdk-docs-for-js/assets/1041352/9e386822-5eab-405e-aa74-d7a25d3326d1">

thanks

**Comment by vineshparamasivam** [comment]
@jmecosta This vulnerability is fixed in 0.0.3 version. https://www.npmjs.com/package/@trimble-oss/trimble-id/v/0.0.3. Hence closing this issue
